---
- name: Infrastructure Provisioning In OCI
  collections:
    - oracle.oci
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - variables.yaml
  tasks:
    - name: Create compartment
      oci_identity_compartment:
        parent_compartment_id: "{{ parent_compartment_id }}"
        name: "{{compartment_name}}"
        description: "SunBird Compartment"
      register: compartment_result

    - set_fact:
        compartment_id: "{{ compartment_result.compartment.id }}"

    - name: Show comp id
      debug:
        msg: |
          Return value is {{ compartment_id }}
